export const FETCH_WEB_SERIES_REQUESTED = 'FETCH_WEB_SERIES_REQUESTED';
export const FETCH_WEB_SERIES_SUCCESS = 'FETCH_WEB_SERIES_SUCCESS';
export const FETCH_WEB_SERIES_FAILED = 'FETCH_WEB_SERIES_FAILED';
