export const FETCH_WEB_SERIES_REQUESTED = 'FETCH_WEB_SERIES_REQUESTED';
export const FETCH_WEB_SERIES_SUCCESS = 'FETCH_WEB_SERIES_SUCCESS';
export const FETCH_WEB_SERIES_FAILED = 'FETCH_WEB_SERIES_FAILED';

export const SEARCH_WEB_SERIES = 'SEARCH_WEB_SERIES';
